### ISSUE TITLE
Error while loading/Feature Request for Preannotations

### ISSUE THREAD

**Issue by pshobowale** [andres-fr/secv-guis#1]
Hey folks,

first of all thanks for this great tool.
I found a bug when loading the preannotations. The code in main_window.py assumes that the annotations are in a .npz fomat while it is depending on the image format so I would recommend you to  change np.load to Image.open. The next thing is that it would be nice if the preannotations are filtered by the current shown image (i.e. if img0.png is displayed only img0.png*_annotation*.png would be suggested). 
I put both changes in my fork. https://github.com/pshobowale/secv-guis

best regards 

Peter Shobowale

**Comment by andres-fr** [comment]
Dear Pete,

Thanks for your kind words. You are right about these things, at the end the project got a bit ad-hoc.

In principle I left this as-is, but if you want to step in I'll be glad to make you a contributor to this repo so you don't need to fork, and maybe I can contribute to your efforts.

The changes you propose and the commit you made in your fork seem 100% meaningful to me (I was the only dev).

Cheers!  
Andres

**Comment by pshobowale** [comment]
Hey Andres,

I guess I could support you as I am using this tool in the moment and during my master thesis. I can not guarantee that I will add many things thought, but I'd like to try to implement my import stuff in a clean way during the next month. I still have one question, how is the threshold meant to be used as I bypass it in the moment? In my case the simple classifiers for the masks do not really support a normal distribution but something multi modal. (based on Variance Filter, DoG.. for abnormalities/scratches in metal surfaces) 

Liebe Grüße
Peter

**Comment by andres-fr** [comment]
Hi Peter,

Sorry if I sounded pushy, you can obviously do whichever you want, as long as you stick to the license I'm fine with it. Do you know how to do [pull requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests)? That's usually the standard way of contributing to OSS, and I think it'd be the best choice here (it has plenty of functionality to inspect/comment code contributions and I could help you that way). Anyway you are probably busy enough with your Msc so this is all just if you have interest.

Note that you can also use `pip install -e` to conveniently install software that is still in development (see e.g. [here](https://stackoverflow.com/questions/42609943/what-is-the-use-case-for-pip-install-e)).

Regarding the threshold: If you are working with binary masks, it has no use. We were working with probability maps, and the threshold could be used to manually balance the precision/recall. Ideally you are able to automatically threshold and work with just the masks (like in your case), but this tool also offers the choice to do it manually for semiautomated/uncalibrated setups.

Another thing that I realize looking at it is that instead of imposing a hardcoded threshold range, we should have used [quantiles](https://numpy.org/doc/stable/reference/generated/numpy.quantile.html). That way the range and resolution of the slider adapt to the nature of the data nicely.

Hope this helps, let me know if you have any other question!
LG
Andres
